version: '3.3'

services:
  mysql:
    image: "mysql:5.7.34"
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "yes"
      MYSQL_USER: pocketbook
      MYSQL_PASSWORD: pocketbook
    ports:
      - "3306:3306"
    volumes:
      - './mysql-datadir:/var/lib/mysql'
      - './mysql-entrypoint-initdb.d:/docker-entrypoint-initdb.d'
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
  postgres:
    image: 'postgres:11-alpine'
    environment:
      POSTGRES_DB: pocketbook
      POSTGRES_USER: pocketbook
      POSTGRES_PASSWORD: pocketbook
    ports:
      - "5432:5432"
    volumes:
      - "./postgres-datadir:/var/lib/postgresql/data"
