# Generated by Django 2.1 on 2020-08-16 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(choices=[('active', 'Активный'), ('passive', 'Пассивный')], max_length=8)),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
                ('whose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Счёт',
                'verbose_name_plural': 'Счета',
            },
        ),
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Остаток')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.Account', verbose_name='Счёт')),
            ],
            options={
                'verbose_name': 'Остаток средств',
                'verbose_name_plural': 'Остатки средств',
            },
        ),
        migrations.CreateModel(
            name='BalanceFixation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(verbose_name='Момент фиксации')),
                ('prev_fixation', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='next_fixation', to='money.BalanceFixation', verbose_name='Предыдущая фиксация')),
            ],
            options={
                'verbose_name': 'Фиксация остатков',
                'verbose_name_plural': 'Фиксации остатков',
                'ordering': ('-when',),
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateTimeField(verbose_name='Дата операции')),
                ('direction', models.CharField(choices=[('debit', 'Дебет'), ('credit', 'Кредит')], max_length=7, verbose_name='Дебет/кредит')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма операции')),
                ('provider', models.CharField(max_length=50, verbose_name='Источник/получатель платежа')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transfers', to='money.Account', verbose_name='Счёт списания/зачисления')),
                ('fixation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transfers', to='money.BalanceFixation', verbose_name='Фиксация, в которой учтена эта операция')),
            ],
            options={
                'verbose_name': 'Операция',
                'verbose_name_plural': 'Операции',
                'ordering': ('-when',),
            },
        ),
        migrations.CreateModel(
            name='TransferDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=3, max_digits=15, verbose_name='Количество товара/услуг')),
                ('value', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Сумма позиции')),
            ],
            options={
                'verbose_name': 'Деталь операции',
                'verbose_name_plural': 'Детали операций',
            },
        ),
        migrations.CreateModel(
            name='TransferReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Описание')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='money.TransferReason', verbose_name='Обобщение')),
            ],
            options={
                'verbose_name': 'Источник/назначение',
                'verbose_name_plural': 'Источники/назначения',
            },
        ),
        migrations.CreateModel(
            name='TransferReasonHierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='money.TransferReason', verbose_name='Корневой элемент иерархии')),
                ('whose', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='transfer_reason_hierarchy', to=settings.AUTH_USER_MODEL, verbose_name='Владелец иерархии')),
            ],
            options={
                'verbose_name': 'Иерархия назначений расходов/источников доходов',
                'verbose_name_plural': 'Иерархии назначений расходов/источников доходов',
            },
        ),
        migrations.AddField(
            model_name='transferdetail',
            name='reason',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='money.TransferReason'),
        ),
        migrations.AddField(
            model_name='transferdetail',
            name='transfer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='money.Transfer', verbose_name='Операция'),
        ),
        migrations.AddField(
            model_name='balance',
            name='fixation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='money.BalanceFixation', verbose_name='Фиксация'),
        ),
        migrations.AlterUniqueTogether(
            name='balance',
            unique_together={('account', 'fixation')},
        ),
    ]
