# Generated by Django 2.1 on 2020-10-04 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField(verbose_name='Дата действия')),
                ('description', models.CharField(blank=True, max_length=800, null=True, verbose_name='Описание')),
                ('elapsed_time', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Затрачено времени (часов)')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Действия',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='Aim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование')),
                ('created', models.DateField(verbose_name='Момент создания записи')),
                ('start_day', models.DateField(null=True, verbose_name='Дата начала')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('estimated_time', models.IntegerField(blank=True, null=True, verbose_name='Оценка времени (часов)')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='aims.Aim', verbose_name='Обобщение')),
            ],
            options={
                'verbose_name': 'Цель',
                'verbose_name_plural': 'Цели',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='AimHierarchy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('root', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='aims.Aim', verbose_name='Корневой элемент иерархии')),
                ('whose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Владелец иерархии')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='action',
            name='aim',
            field=mptt.fields.TreeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='aims.Aim', verbose_name='Цель'),
        ),
    ]
