# Generated by Django 2.1 on 2020-10-09 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aim',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='aim',
            name='done',
            field=models.BooleanField(default=False, verbose_name='Выполнено'),
        ),
    ]
