# Generated by Django 2.1 on 2019-09-01 12:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InsulinInjection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('insulin_quantity',
                 models.PositiveSmallIntegerField(null=True,
                                                  verbose_name='Количество введённого инсулина')),
            ],
            options={
                'verbose_name': 'Инъекция инсулина',
                'verbose_name_plural': 'Инъекции инсулина',
            },
        ),
        migrations.CreateModel(
            name='InsulinKind',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('name',
                 models.CharField(max_length=50, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Вид инсулина',
                'verbose_name_plural': 'Виды инсулина',
            },
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('food_quantity',
                 models.DecimalField(decimal_places=1, max_digits=3,
                                     verbose_name='Количество употреблённых углеводов (ХЕ)')),
            ],
            options={
                'verbose_name': 'Приём пищи',
                'verbose_name_plural': 'Приёмы пищи',
            },
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('when',
                 models.DateTimeField(verbose_name='Момент создания записи')),
                ('who',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   related_name='records',
                                   to=settings.AUTH_USER_MODEL,
                                   verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Запись дневника сахаров',
                'verbose_name_plural': 'Записи дневника сахаров',
            },
        ),
        migrations.CreateModel(
            name='SugarMetering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('sugar_level',
                 models.DecimalField(decimal_places=1, max_digits=3,
                                     verbose_name='Уровень сахара в крови (ммоль/л)')),
                ('record',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE,
                                   to='sugar.Record', verbose_name='Запись')),
            ],
            options={
                'verbose_name': 'Измерение сахара',
                'verbose_name_plural': 'Измерения сахара',
            },
        ),
        migrations.AddField(
            model_name='meal',
            name='record',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='sugar.Record',
                verbose_name='Запись'),
        ),
        migrations.AddField(
            model_name='insulininjection',
            name='insulin_mark',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to='sugar.InsulinKind', verbose_name='Вид инсулина'),
        ),
        migrations.AddField(
            model_name='insulininjection',
            name='record',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='sugar.Record',
                verbose_name='Запись'),
        ),
    ]
