# Generated by Django 2.1 on 2019-09-09 16:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('sugar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True,
                                        serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=400,
                                             verbose_name='Текст комментария')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
        migrations.AlterModelOptions(
            name='record',
            options={'verbose_name': 'Запись дневника сахаров',
                     'verbose_name_plural': 'Записи дневника сахаров'},
        ),
        migrations.AddField(
            model_name='comment',
            name='record',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='sugar.Record',
                verbose_name='Запись'),
        ),
    ]
