# Generated by Django 2.1 on 2020-10-11 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sugar', '0003_meal_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='InsulinOrdering',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('when', models.DateField(verbose_name='Дата выписки')),
                ('next_ordering_plan_date', models.DateField(blank=True, null=True, verbose_name='Планируемая дата следующей выписки')),
                ('insulin_mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sugar.InsulinKind', verbose_name='Вид инсулина')),
                ('whose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Выписка инсулина',
                'verbose_name_plural': 'Выписки инсулина',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='InsulinSyringe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveSmallIntegerField(verbose_name='Номинальный объём')),
                ('opening', models.DateField(verbose_name='Дата начала пользования')),
                ('expiry_plan', models.DateField(blank=True, null=True, verbose_name='Плановая дата окончания пользования')),
                ('expiry_actual', models.DateField(blank=True, null=True, verbose_name='Фактическая дата окончания пользования')),
                ('insulin_mark', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='sugar.InsulinKind', verbose_name='Вид инсулина')),
                ('whose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Шприц',
                'verbose_name_plural': 'Шприцы',
            },
            bases=(models.Model,),
        ),
        migrations.CreateModel(
            name='TestStripPack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('volume', models.PositiveSmallIntegerField(verbose_name='Номинальный объём')),
                ('opening', models.DateField(verbose_name='Дата начала пользования')),
                ('expiry_plan', models.DateField(blank=True, null=True, verbose_name='Плановая дата окончания пользования')),
                ('expiry_actual', models.DateField(blank=True, null=True, verbose_name='Фактическая дата окончания пользования')),
                ('whose', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Пачка тест-полосок',
                'verbose_name_plural': 'Пачки тест-полосок',
            },
            bases=(models.Model,),
        ),
    ]
