# Generated by Django 2.1.5 on 2021-06-13 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sugar', '0005_auto_20210502_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sugarmetering',
            name='record',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='sugar.Record', verbose_name='Запись'),
        ),
    ]
